services:
  airflow-init:
    build: ./airflow
    command: airflow db init #"db init"
    volumes:
      - ./airflow:/opt/airflow  # Map local directory to container

  airflow-webserver:
    build: ./airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__PARALLELISM=32                # Set parallelism
      - AIRFLOW__SCHEDULER__DAG_CONCURRENCY=16        # Set dag_concurrency
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=4 # Set max_active_runs_per_dag
    ports:
      - "8081:8080"
    volumes:
      - ./airflow:/opt/airflow  # Ensure the same volume is shared
    depends_on:
      - airflow-init
    command: bash -c "airflow db upgrade && airflow users create --username admin --firstname Rosalia --lastname Contreras --role Admin --email rosalia.contreras@optimissa.com --password admin && airflow webserver"

  airflow-scheduler:
    build: ./airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__PARALLELISM=32                # Set parallelism
      - AIRFLOW__SCHEDULER__DAG_CONCURRENCY=16        # Set dag_concurrency
      - AIRFLOW__SCHEDULER__MAX_ACTIVE_RUNS_PER_DAG=4 # Set max_active_runs_per_dag
    volumes:
      - ./airflow:/opt/airflow  # Ensure the same volume is shared
    depends_on:
      - airflow-init
    command: airflow scheduler

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8082:8080"  # Spark UI accessible on localhost:8082
    volumes:
      - ./data:/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000" # SonarQube web interface
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:12
    container_name: sonar-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data

volumes:
  sonar_db_data:
